BASE_IMAGE_PREFIX := "ghcr.io/rradczewski/hatter/base/"
BASE_IMAGE_MAX_AGE_DAYS := "30"

YQ_VERSION := "v4.53.6"
YQ_SHA256 := "c5f056448f973ae7d39b5401949648a78f2dc1947d6a8eb65be60d5c504b9385"
TRUNKVER_VERSION := "1.1.3-20260513201613-gf9fdd7b-25823944761-1"
COSIGN_VERSION := "v3.1.3"
COSIGN_SHA256 := "4629c757b7618056f8ddd7e2625ae9fdd94c0372a65049520bc7d9df9efc7f71"

_confirm-install tool version:
  #!/bin/env bash
  set -euo pipefail

  if [ -n "${CI:-}" ]; then
    exit 0
  fi

  read -r -p "Install {{ tool }} {{ version }} to ~/.local/bin? [y/N] " ANSWER
  if [ "$ANSWER" != "y" ]; then
    echo "Not installing {{ tool }}" >&2
    exit 1
  fi

_ensure tool version version_args="--version":
  #!/bin/env bash
  set -euo pipefail

  is_installed() {
    {{ tool }} {{ version_args }} 2>/dev/null | grep -qF "{{ version }}"
  }

  if is_installed; then
    exit 0
  fi

  just "setup-install-{{ tool }}"


setup-install-yq: (_confirm-install "yq" YQ_VERSION)
  #!/bin/env bash
  set -euxo pipefail

  TMP_DIR=$(mktemp -d)
  curl --proto =https --tlsv1.2 -sSfL \
    -o "$TMP_DIR/yq" "https://github.com/mikefarah/yq/releases/download/{{ YQ_VERSION }}/yq_linux_amd64"
  echo "{{ YQ_SHA256 }}  $TMP_DIR/yq" | sha256sum --check

  mkdir -p "$HOME/.local/bin"
  install -m 0755 "$TMP_DIR/yq" "$HOME/.local/bin/yq"

setup-install-cosign: (_confirm-install "cosign" COSIGN_VERSION)
  #!/bin/env bash
  set -euxo pipefail

  TMP_DIR=$(mktemp -d)
  curl --proto =https --tlsv1.2 -sSfL \
    -o "$TMP_DIR/cosign" "https://github.com/sigstore/cosign/releases/download/{{ COSIGN_VERSION }}/cosign-linux-amd64"
  echo "{{ COSIGN_SHA256 }}  $TMP_DIR/cosign" | sha256sum --check

  mkdir -p "$HOME/.local/bin"
  install -m 0755 "$TMP_DIR/cosign" "$HOME/.local/bin/cosign"

setup-install-trunkver: (_confirm-install "trunkver" TRUNKVER_VERSION) (_ensure "cosign" COSIGN_VERSION "version")
  #!/bin/env bash
  set -euxo pipefail

  TMP_DIR=$(mktemp -d)
  cd "$TMP_DIR"
  curl --proto =https --tlsv1.2 -sSfL \
    -o trunkver_linux_amd64 "https://github.com/crftd-tech/trunkver/releases/download/{{ TRUNKVER_VERSION }}/trunkver_linux_amd64" \
    -o trunkver_linux_amd64.cosign.bundle "https://github.com/crftd-tech/trunkver/releases/download/{{ TRUNKVER_VERSION }}/trunkver_linux_amd64.cosign.bundle" \
    -o checksums.txt "https://github.com/crftd-tech/trunkver/releases/download/{{ TRUNKVER_VERSION }}/checksums.txt" \
    -o checksums.txt.cosign.bundle "https://github.com/crftd-tech/trunkver/releases/download/{{ TRUNKVER_VERSION }}/checksums.txt.cosign.bundle"

  cosign verify-blob \
    "checksums.txt" \
    --bundle "checksums.txt.cosign.bundle" \
    --certificate-identity=https://github.com/crftd-tech/trunkver/.github/workflows/build.yml@refs/heads/main \
    --certificate-oidc-issuer=https://token.actions.githubusercontent.com

  shasum --algorithm 256 --ignore-missing --check checksums.txt

  cosign verify-blob \
    "trunkver_linux_amd64" \
    --bundle "trunkver_linux_amd64.cosign.bundle" \
    --certificate-identity=https://github.com/crftd-tech/trunkver/.github/workflows/build.yml@refs/heads/main \
    --certificate-oidc-issuer=https://token.actions.githubusercontent.com

  mkdir -p "$HOME/.local/bin"
  install -m 0755 trunkver_linux_amd64 "$HOME/.local/bin/trunkver"

# Mirrors the newest maintained Fedora versions (excluding rawhide) to base-images.yaml
discover_base_images: (_ensure "yq" YQ_VERSION)
  #!/bin/env bash
  set -xeuo pipefail

  manifest_hash() {
    skopeo inspect --raw "docker://$1" | sha256sum | cut -d' ' -f1
  }

  maintained_tags() {
    local REPO="$1"
    local SUFFIX="$2"

    local VERSIONS
    VERSIONS=$(skopeo list-tags "docker://$REPO" | yq -p json '.Tags[]' | grep -E '^[0-9]+$' | sort -n)

    local RAWHIDE_HASH RAWHIDE_VERSION=""
    RAWHIDE_HASH=$(manifest_hash "$REPO:rawhide")
    for VERSION in $VERSIONS; do
      if [ "$(manifest_hash "$REPO:$VERSION")" == "$RAWHIDE_HASH" ]; then
        RAWHIDE_VERSION="$VERSION"
      fi
    done
    if [ -z "$RAWHIDE_VERSION" ]; then
      echo "Could not determine the rawhide version of $REPO" >&2
      exit 1
    fi

    for VERSION in $(echo "$VERSIONS" | awk -v rawhide="$RAWHIDE_VERSION" '$1 < rawhide' | tail -3); do
      local IMAGE="$REPO:$VERSION$SUFFIX"
      local AGE_DAYS
      AGE_DAYS=$(just _image_age_days "$IMAGE")
      if [ "$AGE_DAYS" -le "{{ BASE_IMAGE_MAX_AGE_DAYS }}" ]; then
        echo "$IMAGE"
      else
        echo "Skipping $IMAGE, last updated $AGE_DAYS days ago" >&2
      fi
    done
  }

  IMAGES=$(
    maintained_tags quay.io/fedora/fedora-silverblue -x86_64
    maintained_tags quay.io/fedora-ostree-desktops/base-atomic ""
  )

  IMAGES="$IMAGES" yq -n \
    '.images = (strenv(IMAGES) | split("\n")) | . head_comment = "Generated by `just discover_base_images`, do not edit"' \
    > base-images.yaml
  cat base-images.yaml

list_base_images: (_ensure "yq" YQ_VERSION)
  yq '.images[]' base-images.yaml

_image_age_days image:
  #!/bin/env bash
  set -euo pipefail

  CREATED=$(skopeo inspect --format "{{ "{{.Created.Unix}}" }}" "docker://{{ image }}")
  echo $(( ($(date +%s) - CREATED) / 86400 ))

assert_base_image_fresh hat:
  #!/bin/env bash
  set -euo pipefail

  BASE_IMAGE=$(grep -oP '^BASE_IMAGE=\K(.+)' "{{ hat }}/render.sh")
  AGE_DAYS=$(just _image_age_days "${BASE_IMAGE//:*@/@}")

  if [ "$AGE_DAYS" -gt "{{ BASE_IMAGE_MAX_AGE_DAYS }}" ]; then
    echo "Base image of {{ hat }} is $AGE_DAYS days old (max {{ BASE_IMAGE_MAX_AGE_DAYS }}): $BASE_IMAGE" >&2
    exit 1
  fi
  echo "Base image of {{ hat }} is $AGE_DAYS days old"

rotate_base_image image:
  #!/bin/env bash
  set -euxo pipefail

  SOURCE_IMAGE="{{ image }}"
  IMAGE_PATH=${SOURCE_IMAGE#*/}

  TARGET_IMAGE_NEXT="{{ BASE_IMAGE_PREFIX }}${IMAGE_PATH}-next"
  TARGET_IMAGE_NOW="{{ BASE_IMAGE_PREFIX }}${IMAGE_PATH}-now"

  NEW_IMAGE=$(skopeo inspect --format "{{ "{{.Name}}@{{.Digest}}" }}" "docker://$SOURCE_IMAGE")
  
  set +e
  if ! skopeo inspect "docker://${TARGET_IMAGE_NEXT}" 2>&1 > /dev/null; then
    echo "No next image, copying new next to current next"
    skopeo copy --all "docker://$NEW_IMAGE" "docker://${TARGET_IMAGE_NEXT}"
  fi
  set -e

  skopeo copy "docker://$TARGET_IMAGE_NEXT" "docker://${TARGET_IMAGE_NOW}"
  skopeo copy "docker://$NEW_IMAGE" "docker://${TARGET_IMAGE_NEXT}"


generate_temporary_signing_keys:
  #!/bin/env bash
  mkdir -p ./tmp/kernel_signing_key/ || true
  openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 > ./tmp/kernel_signing_key/kernel_signing_certificate_key.key
  openssl req -x509 -key ./tmp/kernel_signing_key/kernel_signing_certificate_key.key -subj /CN=github.com/CN=rradczewski/CN=hatter/CN=CI_THROAWAY_KEY_DO_NOT_TRUST > ./tmp/kernel_signing_key/kernel_signing_certificate_key.pem

list-as-json cmd:
  just "{{cmd}}" |  jq -R '.' | jq -sc '.'

list-changed-hats:
  #!/usr/bin/env bash
  set -euxo pipefail

  changed_folders=$(
    git diff --name-only origin/main...HEAD \
      | cut -d'/' -f1 \
      | sort -u
  )

  subtasks=$(just list-hats | sort -u)

  comm -12 <(echo "$changed_folders") <(echo "$subtasks")

list-hats:
  find . -maxdepth 1 -mindepth 1 -type d \
    -not -name '.*' \
    -not -name '_*' \
    -not -name tmp \
    -not -name out \
    -printf '%f\n'

render hat: (_ensure "trunkver" TRUNKVER_VERSION)
  ./_tooling/render_hat.sh "{{ hat }}"

build hat: (render hat) (assert_base_image_fresh hat)
  #!/bin/env bash
  set -eo pipefail

  if [ -z "$KERNEL_SIGNING_CERTIFICATE_KEY" ] || [ -z "$KERNEL_SIGNING_CERTIFICATE_PEM" ]; then
    echo "Generating temporary signing keys"
    just generate_temporary_signing_keys
    export KERNEL_SIGNING_CERTIFICATE_KEY=$(cat ./tmp/kernel_signing_key/kernel_signing_certificate_key.key)
    export KERNEL_SIGNING_CERTIFICATE_PEM=$(cat ./tmp/kernel_signing_key/kernel_signing_certificate_key.pem)
  else 
    echo "Using existing signing keys"

    PUBKEY_FROM_REPO=$(cat "./signing_key.pub" | openssl x509 -noout -pubkey)
    PUBKEY_FROM_PRIVATE_KEY=$(echo "$KERNEL_SIGNING_CERTIFICATE_KEY" | openssl pkey -pubout)
    PUBKEY_FROM_CERTIFICATE=$(echo "$KERNEL_SIGNING_CERTIFICATE_PEM" | openssl x509 -noout -pubkey)
    if [ "$PUBKEY_FROM_REPO" != "$PUBKEY_FROM_CERTIFICATE" ] || [ "$PUBKEY_FROM_CERTIFICATE" != "$PUBKEY_FROM_PRIVATE_KEY" ] || [ -z "$PUBKEY_FROM_CERTIFICATE" ] || [ -z "$PUBKEY_FROM_PRIVATE_KEY" ];
    then
      echo "Pubkeys don't match"
      echo "Repo: $PUBKEY_FROM_REPO"
      echo "Private Key: $PUBKEY_FROM_PRIVATE_KEY"
      echo "Pub: $PUBKEY_FROM_CERTIFICATE"
      exit 1
    fi
  fi

  set -euxo pipefail

  source "out/{{ hat }}.meta"

  BUILDAH_OPT=""
  set +u
  if [ "$GITHUB_REF" == "refs/heads/main" ]; then
    BUILDAH_OPT="--cache-to=ghcr.io/rradczewski/hatter-cache"
  fi
  set -u

  IIDFILE="out//{{ hat }}.iid"
  buildah \
    build \
    --cache-ttl=168h \
    --cache-from=ghcr.io/rradczewski/hatter-cache \
    $BUILDAH_OPT \
    --iidfile "$IIDFILE" \
    --layers \
    --format oci \
    --secret id=KERNEL_SIGNING_CERTIFICATE_KEY,env=KERNEL_SIGNING_CERTIFICATE_KEY \
    --secret id=KERNEL_SIGNING_CERTIFICATE_PEM,env=KERNEL_SIGNING_CERTIFICATE_PEM \
    -t "$IMAGE_TAG" \
    -f "out/{{ hat }}.Containerfile" \
    .
  
  cat "$IIDFILE"

push hat:
  #!/bin/env bash
  set -euxo pipefail

  source "out/{{ hat }}.meta"
  IMAGE_ID=$(cat "out/{{ hat }}.iid")
  DIGESTFILE="out//{{ hat }}.digest"
  buildah push --digestfile "$DIGESTFILE" "$IMAGE_ID" "docker://$IMAGE_TAG"
  buildah push "$IMAGE_ID" "docker://$IMAGE:edge"

sign hat: (_ensure "cosign" COSIGN_VERSION "version")
  #!/bin/env bash
  set -euxo pipefail

  source "out/{{ hat }}.meta"
  DIGEST=$(cat "out/{{ hat }}.digest")
  cosign sign --verbose --yes ${IMAGE}@${DIGEST}

iso hat:
  #!/bin/env bash
  set -euxo pipefail

  source "out/{{ hat }}.meta"
  IMAGE_ID=$(cat "out/{{ hat }}.iid")
  DIGEST=$(podman inspect "${IMAGE_ID#sha256:}" --format {{ "{{.Digest}}" }})

  OUT_DIR="./out/{{ hat }}.iso/"
  mkdir "$OUT_DIR" || true

  sudo skopeo copy \
    'containers-storage:[overlay@'$HOME'/.local/share/containers/storage+/run/user/'$(id -u)'/containers]'${IMAGE}@${DIGEST} \
    'containers-storage:[overlay@/var/lib/containers/storage]'${IMAGE_TAG}
  
  sudo podman run \
    --rm \
    -it \
    --privileged \
    --security-opt label=type:unconfined_t \
    -v "$OUT_DIR":/output \
    --volume "./_tooling/anaconda-iso.toml:/config.toml:z" \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest@sha256:754fc17718f977313885379e2c779066aba7d15af88fe04b486baec74759f574 \
    --rootfs btrfs \
    --verbose \
    --type anaconda-iso \
    ${IMAGE}@${DIGEST}
  sudo chown $(id -u) -vR "$OUT_DIR"

vm hat:
  #!/bin/env bash
  set -euxo pipefail

  source "out/{{ hat }}.meta"
  IMAGE_ID=$(cat "out/{{ hat }}.iid")
  DIGEST=$(podman inspect "${IMAGE_ID#sha256:}" --format {{ "{{.Digest}}" }})

  OUT_DIR="./out/{{ hat }}.vm/"
  mkdir "$OUT_DIR" || true

  sudo skopeo copy \
    'containers-storage:[overlay@'$HOME'/.local/share/containers/storage+/run/user/'$(id -u)'/containers]'${IMAGE}@${DIGEST} \
    'containers-storage:[overlay@/var/lib/containers/storage]'${IMAGE_TAG}
  
  sudo podman run \
    --rm \
    -it \
    --volume "./{{ hat }}/config.toml:/config.toml:z" \
    --privileged \
    --security-opt label=type:unconfined_t \
    -v "$OUT_DIR":/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest@sha256:754fc17718f977313885379e2c779066aba7d15af88fe04b486baec74759f574 \
    --rootfs btrfs \
    --verbose \
    --type qcow2 \
    ${IMAGE}@${DIGEST}
  sudo chown $(id -u) -vR "$OUT_DIR"

update-digest hat:
  #!/bin/env bash
  set -euxo pipefail

  CURRENT_REF=$(grep -oP '^BASE_IMAGE=\K(.+)' "{{ hat }}/render.sh")
  CURRENT_REF_WITHOUT_DIGEST=${CURRENT_REF//@*/}

  NEW_DIGEST=$(skopeo inspect "docker://${CURRENT_REF_WITHOUT_DIGEST}" --format "{{ "{{ .Digest }}" }}")

  UPDATED_REF=${CURRENT_REF_WITHOUT_DIGEST}@${NEW_DIGEST}

  sed -i 's|^BASE_IMAGE=.*$|BASE_IMAGE='${UPDATED_REF}'|' "{{ hat }}/render.sh"
