[terminal]
vt = 1

[default_session]
command = "tuigreet --remember --time --user-menu --cmd niri-session --theme 'border=lightmagenta;text=cyan;prompt=lightmagenta;action=lightcyan;container=black;input=white'"
user = "greeter"