name: Build hats
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
  workflow_dispatch:

permissions:
  packages: write
  id-token: write
  attestations: write

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}


jobs:
  list-hats:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - id: set-matrix
        run: echo "::set-output name=matrix::$(find . -maxdepth 1 -mindepth 1 -type d -not -name .github -not -name _common -not -name .git -not -name _tooling -not -name out -printf '%f\n' | jq -R -s -c 'split("\n")[:-1]')"

  build-image:
    name: Build and push image
    needs: [list-hats]
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'main' || '' }}
    strategy:
        max-parallel: 1
        matrix:
            hat: ${{ fromJson(needs.list-hats.outputs.matrix) }}

    outputs:
      registry-path: ${{ steps.push.outputs.registry-path }}
    steps:
      - name: Setup cosign
        if: github.ref == 'refs/heads/main'
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
        with:
          cosign-release: "v2.6.0"

      - name: Install just
        run: |
          sudo apt-get update
          sudo apt-get install just --yes

      - name: Install trunkver
        run: |
          set -x
          TMP_DIR=$(mktemp -d)
          cd "$TMP_DIR"
          curl --proto =https --tlsv1.2 -sSfL -O \
            "https://github.com/crftd-tech/trunkver/releases/download/1.1.3-20260513201613-gf9fdd7b-25823944761-1/trunkver_linux_amd64" \
            "https://github.com/crftd-tech/trunkver/releases/download/1.1.3-20260513201613-gf9fdd7b-25823944761-1/trunkver_linux_amd64.cosign.bundle" \
            "https://github.com/crftd-tech/trunkver/releases/download/1.1.3-20260513201613-gf9fdd7b-25823944761-1/checksums.txt" \
            "https://github.com/crftd-tech/trunkver/releases/download/1.1.3-20260513201613-gf9fdd7b-25823944761-1/checksums.txt.cosign.bundle"

          cosign verify-blob \
            "checksums.txt" \
            --bundle "checksums.txt.cosign.bundle" \
            --certificate-identity=https://github.com/crftd-tech/trunkver/.github/workflows/build.yml@refs/heads/main \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com

          shasum --algorithm 256 --ignore-missing --check checksums.txt

          cosign verify-blob \
            "trunkver_linux_amd64" \
            --bundle "trunkver_linux_amd64.cosign.bundle" \
            --certificate-identity=https://github.com/crftd-tech/trunkver/.github/workflows/build.yml@refs/heads/main \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com
          
          cp "trunkver_linux_amd64" "~/.local/bin/trunkver"


      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
      
      - name: Build image
        run: |
          just build "${{ matrix.hat }}"
          just push "${{ matrix.hat }}"
        env:
          KERNEL_SIGNING_CERTIFICATE_PEM: ${{ secrets.KERNEL_SIGNING_CERTIFICATE_PEM }}
          KERNEL_SIGNING_CERTIFICATE_KEY: ${{ secrets.KERNEL_SIGNING_CERTIFICATE_KEY }}

      - name: Sign docker image
        if: github.ref == 'refs/heads/main'
        run: just sign "${{ matrix.hat }}"
